### ISSUE TITLE
Plugin does not seem to be working correctly with latest Embla Version

### ISSUE THREAD

**Issue by janwidmer** [nwidynski/embla-carousel-aria#1]
Hi There,

I tried your Plugin with the latest Version of Embla Carousel. When the slides contain a link, it seems, that I cannot navigate to the link within the first slide..

You can see an example here: https://codesandbox.io/p/sandbox/embla-carousel-slides-per-view-vanilla-forked-2x4vhj.

Are you planning on releasing a non RC version soon or was this more sort of a tryout?

**Comment by nwidynski** [comment]
Hey @janwidmer 

Sorry for the late reply. This issue occurs because you set the inViewThreshold to 100%, which isn't the case for the first slide. When you set it to 90% the issue, the issue should be solved. Let me know if there is any reason to keep this at 100% for your use-case.

**Comment by janwidmer** [comment]
Hey @nwidynski,

No worries.. I don't exactly recall, why I choose`inViewThreshold` of 1 over 0.9. The other question is, if you could adjust it, so it doesn't matter, which `inViewThreshold` is set.. Such implicit combinations of required options is usually not ideal..

Regarding a test suite, which framework do you have in mind for creating tests?

**Comment by nwidynski** [comment]
@janwidmer The behavior of whether a slide is in view is controlled by Embla itself. The`inViewThreshold` property specifically controls the IntersectionObserver on the slides. This plugin attaches to Embla's decision and just considers any slide that is currently in view as actionable & tabbable.

It does not matter whether its any specific value as long as the slide is actually in view by that percentage. Usually slides are not in view by 100% due to the way carousels are styled in CSS. I made a change to the README.md to take note of this correlation.

As for the testing framework, I currently like to write my stuff in either Jest or Vitest.

**Comment by janwidmer** [comment]
@nwidynski taking `inViewThreshold` as reference makes sense. But when you check my example https://codesandbox.io/p/sandbox/embla-carousel-slides-per-view-vanilla-forked-2x4vhj, when using `inViewThreshold` of 1, the first visible slide (most left) is not tabbable, and not the last visible one (3rd slide). And all of them are completely visible (no partial view via css). 

In that case, in my understanding, also all 3 slides should be tabbable?

**Comment by nwidynski** [comment]
@janwidmer The `inViewThreshold` is taken from the `.embla_viewport` element. I've attached two screenshots displaying your slide overlapping this viewport because of its `padding`.

![image](https://github.com/nwidynski/embla-carousel-aria/assets/25958801/6d892090-471b-4b65-a036-2313d62a3c15)
![image](https://github.com/nwidynski/embla-carousel-aria/assets/25958801/be0e9334-1b85-431b-a7f5-951c678fbdb7)

**Comment by janwidmer** [comment]
@nwidynski ah, that makes sense, thanks for checking.. The thing is though, that the left padding is the standard way of having spacing between the slides and have the left most slide still starting at the vertical context of the surrounding element.

You can see that in this ootb example directly generated from the embla examples page: https://codesandbox.io/s/8g7z7s.

I guess, I just have to use 90% inViewTreshold always then..
